# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orgLayout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_prepare2Pg(object):
    def setupUi(self, prepare2Pg):
        prepare2Pg.setObjectName(_fromUtf8("prepare2Pg"))
        prepare2Pg.resize(1304, 777)
        self.centralwidget = QtGui.QWidget(prepare2Pg)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 390, 941, 211))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 1021, 191))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.optARadioButton = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optARadioButton.setFont(font)
        self.optARadioButton.setObjectName(_fromUtf8("optARadioButton"))
        self.buttonGroup = QtGui.QButtonGroup(prepare2Pg)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.optARadioButton)
        self.verticalLayout_3.addWidget(self.optARadioButton)
        self.optBRadioButton = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optBRadioButton.setFont(font)
        self.optBRadioButton.setObjectName(_fromUtf8("optBRadioButton"))
        self.buttonGroup.addButton(self.optBRadioButton)
        self.verticalLayout_3.addWidget(self.optBRadioButton)
        self.optCRadioButton = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optCRadioButton.setFont(font)
        self.optCRadioButton.setObjectName(_fromUtf8("optCRadioButton"))
        self.buttonGroup.addButton(self.optCRadioButton)
        self.verticalLayout_3.addWidget(self.optCRadioButton)
        self.optDRadioButton = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optDRadioButton.setFont(font)
        self.optDRadioButton.setObjectName(_fromUtf8("optDRadioButton"))
        self.buttonGroup.addButton(self.optDRadioButton)
        self.verticalLayout_3.addWidget(self.optDRadioButton)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 120, 941, 261))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.QuestionLabel = QtWebKit.QWebView(self.layoutWidget2)
        self.QuestionLabel.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.QuestionLabel.setObjectName(_fromUtf8("QuestionLabel"))
        self.horizontalLayout_4.addWidget(self.QuestionLabel)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 610, 941, 51))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.previousBtn = QtGui.QPushButton(self.layoutWidget3)
        self.previousBtn.setMaximumSize(QtCore.QSize(100, 70))
        self.previousBtn.setObjectName(_fromUtf8("previousBtn"))
        self.horizontalLayout_2.addWidget(self.previousBtn)
        self.nextBtn = QtGui.QPushButton(self.layoutWidget3)
        self.nextBtn.setMaximumSize(QtCore.QSize(100, 70))
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_2.addWidget(self.nextBtn)
        self.reviewBtn = QtGui.QPushButton(self.layoutWidget3)
        self.reviewBtn.setMaximumSize(QtCore.QSize(100, 70))
        self.reviewBtn.setObjectName(_fromUtf8("reviewBtn"))
        self.horizontalLayout_2.addWidget(self.reviewBtn)
        self.submitBtn = QtGui.QPushButton(self.layoutWidget3)
        self.submitBtn.setMaximumSize(QtCore.QSize(100, 70))
        self.submitBtn.setObjectName(_fromUtf8("submitBtn"))
        self.horizontalLayout_2.addWidget(self.submitBtn)
        self.endTestBtn = QtGui.QPushButton(self.layoutWidget3)
        self.endTestBtn.setMaximumSize(QtCore.QSize(100, 70))
        self.endTestBtn.setObjectName(_fromUtf8("endTestBtn"))
        self.horizontalLayout_2.addWidget(self.endTestBtn)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(9, 9, 1191, 111))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.medPg = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.medPg.setFont(font)
        self.medPg.setObjectName(_fromUtf8("medPg"))
        self.horizontalLayout.addWidget(self.medPg)
        self.testNameLabel = QtGui.QLabel(self.layoutWidget4)
        self.testNameLabel.setObjectName(_fromUtf8("testNameLabel"))
        self.horizontalLayout.addWidget(self.testNameLabel)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber.setMaximumSize(QtCore.QSize(150, 70))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(950, 120, 261, 541))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget = QtGui.QWidget(self.layoutWidget5)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(0, -2, 241, 541))
        self.scrollArea.setStyleSheet(_fromUtf8(""))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 222, 522))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.widget)
        prepare2Pg.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(prepare2Pg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        prepare2Pg.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(prepare2Pg)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        prepare2Pg.setStatusBar(self.statusbar)

        self.retranslateUi(prepare2Pg)
        QtCore.QMetaObject.connectSlotsByName(prepare2Pg)

    def retranslateUi(self, prepare2Pg):
        prepare2Pg.setWindowTitle(_translate("prepare2Pg", "MainWindow", None))
        self.groupBox.setTitle(_translate("prepare2Pg", "GroupBox", None))
        self.optARadioButton.setText(_translate("prepare2Pg", "RadioButton", None))
        self.optBRadioButton.setText(_translate("prepare2Pg", "RadioButton", None))
        self.optCRadioButton.setText(_translate("prepare2Pg", "RadioButton", None))
        self.optDRadioButton.setText(_translate("prepare2Pg", "RadioButton", None))
        self.previousBtn.setText(_translate("prepare2Pg", "Previous", None))
        self.nextBtn.setText(_translate("prepare2Pg", "Next", None))
        self.reviewBtn.setText(_translate("prepare2Pg", "Mark for review", None))
        self.submitBtn.setText(_translate("prepare2Pg", "Submit", None))
        self.endTestBtn.setText(_translate("prepare2Pg", "End Test", None))
        self.medPg.setText(_translate("prepare2Pg", "<html><head/><body><p align=\"center\"><span style=\" color:#ff5500;\">Prepare2Pg</span></p></body></html>", None))
        self.testNameLabel.setText(_translate("prepare2Pg", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#0000ff;\">Mock Test - 1</span></p></body></html>", None))

from PyQt4 import QtWebKit
